CPP = c++
CPPFLAGS = -Wall -Wextra -Werror
SRCS = main.cpp BitcoinExchange.cpp
NAME = btc

all: $(NAME)

$(NAME): $(SRCS)
	$(CPP) $(CPPFLAGS) $(SRCS) -o $(NAME)

clean:
	rm -rf $(NAME)

fclean: clean
	rm -rf $(NAME)

re: clean all

















